function plot_rd( m, problem, varargin )

% mysql parameters
outfile_base = '/tmp/matlab_mysql';
outfile_end = '.txt';
system_call  = 'mysql omrp -Be ''';
mysql_select =  'SELECT gamma';
for ii = 1:length(varargin)
    mysql_select = [mysql_select ',' varargin{ii}];
end
mysql_from   =  ' FROM run_data INNER JOIN ';
mysql_latest = [' ( SELECT a.name,a.problem,a.batch_size ' ...
                '  FROM run_desc AS a WHERE NOT EXISTS ' ...
                '  ( SELECT * FROM run_desc AS b ' ...
                '   WHERE a.problem=b.problem ' ...
                '    AND a.batch_size=b.batch_size ' ...
                '    AND b.date>a.date ' ...
                ' ) ) AS latest ' ];
mysql_on     =  ' ON run_data.name = latest.name';
mysql_where  = [' WHERE latest.problem="' problem '"' ...
                ' AND latest.batch_size = '];
mysql_order  =  ' ORDER BY gamma'''; % Must be ascending order
% system_redir = [' > ' outfile];

for ii = 1:length(m)
    system([ system_call ...
        mysql_select mysql_from mysql_latest mysql_on ...
        mysql_where num2str(m(ii)) mysql_order ...
        ' > ' outfile_base num2str(m(ii)) outfile_end]);
end

plot_files( m, outfile_base, outfile_end );
