/*------------------------------------------------------------------------------
MODULE TYPE:		Linear optimization supporting header
PROJECT CODE:		Simplex.
PROJECT FULL NAME:	Advanced implementation of revised simplex method
					for large scale linear problems.

MODULE AUTHOR:		Artur Swietanowski.

PROJECT SUPERVISOR:	prof. Andrzej P. Wierzbicki

--------------------------------------------------------------------------------

HEADER FILE NAME:	lp_sol.h
CREATED:			1995.03.03
LAST MODIFIED:		1996.06.21

DEPENDENCIES:		solution.h, stdtype.h, smartptr.h, mps_lp.h
					<stdio.h>

--------------------------------------------------------------------------------

HEADER CONTENTS:
	The header contains a declaration of a structure used for holding a linear
program solution, possibly generated by a simplex optimizaer.

------------------------------------------------------------------------------*/

#ifndef __LP_SOL_H__
#define __LP_SOL_H__

#ifndef __SOL_LAB_H__
#	include "sol_lab.h"
#endif
#ifndef __MPS_LP_H__
#	include "mps_lp.h"
#endif

#ifdef SUPPORT_LP_DIT
#	include "lp_dit.h"
#endif


//==============================================================================
//
//	Structure "Solution" declaration.
//

class LP_Solution : public SolutionWithLabels
{
private:
	MPS_LP *LP;

public:
	LP_Solution( void );
	LP_Solution( MPS_LP *lp, int cntnts = Empty );

	virtual ~LP_Solution( void );

	virtual void SetLP( MPS_LP &lp );

	virtual void WriteText( FILE *fp, int cntnts = Empty ) const;
};

//
//	End of structure "Solution" declaration.
//
//==============================================================================

inline
LP_Solution::LP_Solution( void )
	: LP( NULL )
{}


inline
LP_Solution::~LP_Solution( void )
{}


#endif
